select* from customer

--Q1. What is the total revenue generated by male vs. female customers?
select "gender" ,sum("purchase_amount")as revenue from customer
group by "gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select "Customer_ID","Purchase_amount"
from customer
where "Discount_Applied" = 'Yes' and "Purchase_amount"> (select avg("Purchase_amount")from customer)


--Q3. Which are the top 5 products with the highest review rating but still low revenue?
select "item_purchased",Round(max("review_rating"::numeric),2)as review_rating,sum(purchase_amount)as revenue
from customer
group by "item_purchased"
order by revenue 
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select round(avg("purchase_amount"),2),"shipping_type"
from customer
where "shipping_type" in('Express','Standard')
group by "shipping_type"

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select "subscription_status",
avg("purchase_amount"), as average
sum("purchase_amount")as revenue
from customer
group by "subscription_status"
order by revenue

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select "item_purchased",
round(100*sum(case when"discount_applied"='Yes'then 1 else 0 end)/count(*),2)as discount_rate
from customer
Group by "item_purchased"
order by discount_rate desc
limit 5


--Q7. Segment customers into New, Returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment.
with customer_type as(
select "customer_id","previous_purchases",
case 
when "previous_purchases"=1 then 'New'
when "previous_purchases" between 2 and 10 then 'Rutrening'
else 'Loyal'
end as customer_segment
from customer
)
select customer_segment ,count(*)as no_of_customer
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_count as (
select "category","item_purchased",
count("customer_id")as total_order,
row_number() over (partition by "category" order by count ("customer_id")desc)as item_rank
from customer
group by "item_purchased","category"

)
select "item_purchased",item_rank,"category","total_order"
from item_count
where item_rank<=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) 
--also likely to subscribe?
select "subscription_status",count("customer_id")as repeat_buyers
from customer
where "previous_purchases">5
group by "subscription_status"

--Q10. What is the revenue contribution of each age group?
select age_group,sum("purchase_amount")
from customer
group by age_group